### ISSUE TITLE
Problem running on older GPUs

### ISSUE THREAD

**Issue by hpourreza** [soumith/convnet-benchmarks#119]
I can run the Theano benchmark on K80 using Cuda 8.0 and Python/2.7.12 but when I try to run it on older GPUs (K20 or M2090) using cuda 7.5 and python 2.7.9 the program gets killed:

```
$ SKIP=legacy python pylearn2_benchmark.py 
Using gpu device 0: Tesla M2090 (CNMeM is disabled, cuDNN not available)
Note: cuDNN not available

CONFIG: input = 3 x 128 x 128 * ker = 3 x 96 x 11 x 11 ( bs = 128 , stride = 1 )
Killed
```
Any idea why this is happening?

**Comment by nouiz** [comment]
Doing benchmark without cudnn isn't useful. Can you install it? It could
also fix your problem.

If not, I have the impression that it get killed by the OS. Are you testing
it on a cluster? Did you request enough CPU memory? If not, many job
scheduler could kill your job with that message.

Le 6 déc. 2016 21:37, "hpourreza" <notifications@github.com> a écrit :

I can run the Theano benchmark on K80 using Cuda 8.0 and Python/2.7.12 but
when I try to run it on older GPUs (K20 or M2090) using cuda 7.5 and python
2.7.9 the program gets killed:

$ SKIP=legacy python pylearn2_benchmark.py
Using gpu device 0: Tesla M2090 (CNMeM is disabled, cuDNN not available)
Note: cuDNN not available

CONFIG: input = 3 x 128 x 128 * ker = 3 x 96 x 11 x 11 ( bs = 128 , stride = 1 )
Killed

Any idea why this is happening?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/soumith/convnet-benchmarks/issues/119>, or mute the
thread

**Comment by hpourreza** [comment]
Thanks @nouiz. I was asking for 2GB of memory but apparently it was not enough. I increased it and the code started running.
I can see `libcudnn.so.x` files within the CUDA installation but for some reason `dnn_available()` returns `False`.
